services:
  - type: web
    name: gestao-karate-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade || (flask db migrate -m "Auto migration" && flask db upgrade)
    startCommand: gunicorn src.app:app
    envVars:
      - key: FLASK_APP
        value: src.app
      - key: FLASK_ENV
        value: production
