services:
  - type: web
    name: gestao-karate-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade || (flask db migrate -m "Add missing columns" && flask db upgrade)
    startCommand: gunicorn app:app
